/**
 * [실행 순서 2단계: HTML 레이아웃 셸 정의 (app/layout.tsx)]
 * Next.js App Router의 루트 레이아웃 파일입니다.
 * 이 파일은 웹 사이트의 모든 페이지(page.tsx)를 감싸는 HTML 기본 구조(html, body)를 생성합니다.
 */

// 2.1: 외부 모듈 및 스타일시트 가져오기
import type { Metadata } from "next"; // SEO(검색엔진 최적화)를 위한 메타데이터 타입 정의
import { Geist, Geist_Mono } from "next/font/google"; // 구글 폰트를 Next.js 빌드 시점에 최적화하여 가져오기
import "./globals.css"; // 1단계에서 정의한 테마 및 전역 스타일시트를 적용

// 2.2: 웹 폰트(Geist) 인스턴스 생성 및 CSS 변수 지정
// subsets: ["latin"]은 라틴 문자셋만 경량화하여 다운로드하도록 최적화합니다.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 2.3: SEO 메타데이터 설정 (HTML의 <head> 태그 내부에 메타 태그로 주입됨)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 2.4: 루트 레이아웃 컴포넌트 (RootLayout)
// Next.js는 이 컴포넌트를 호출하고, 요청받은 페이지(children)를 body 태그 내부에 주입합니다.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // ReactNode 타입은 문자열, JSX, 컴포넌트 등 모든 렌더링 가능 대상을 포함합니다.
}>) {
  return (
    <html
      lang="en"
      // 폰트 클래스와 함께 전체 화면 높이(h-full) 및 폰트 부드럽게 설정(antialiased) 적용
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* 2.5: body 내부에서 {children}을 출력하여 개별 page.tsx의 내용이 렌더링되게 함 */}
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}

