/**
 * [실행 순서 2단계: HTML 레이아웃 셸 정의 (app/layout.tsx)]
 * Next.js App Router의 루트 레이아웃 파일입니다.
 * 이 파일은 웹 사이트의 모든 페이지(page.tsx)를 감싸는 HTML 기본 구조(html, body)를 생성합니다.
 */

// 2.1: 외부 모듈 및 스타일시트 가져오기
import type { Metadata } from "next"; // SEO(검색엔진 최적화)를 위한 메타데이터 타입 정의
import { Geist, Geist_Mono } from "next/font/google"; // 구글 폰트를 Next.js 빌드 시점에 최적화하여 가져오기
import "./globals.css"; // 1단계에서 정의한 테마 및 전역 스타일시트를 적용

// 2.2: 웹 폰트(Geist) 인스턴스 생성 및 CSS 변수 지정
// subsets: ["latin"]은 라틴 문자셋만 경량화하여 다운로드하도록 최적화합니다.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

/* 
 * [문법 요소 하나하나 상세 설명]
 * 1. const: 재할당이 불가능한 상수를 선언하는 자바스크립트/타입스크립트 키워드입니다.
 * 2. geistMono: 폰트 객체 인스턴스를 담기 위해 개발자가 지정한 상수 이름(식별자)입니다.
 * 3. =: 대입(할당) 연산자로, 우변의 함수 호출 결과를 좌변의 geistMono 상수에 대입합니다.
 * 4. Geist_Mono: 9번 라인의 import에서 가져온 Google Fonts 모듈의 폰트 생성 함수(폰트 로더)입니다.
 * 5. ( (소괄호 열기): Geist_Mono 함수를 호출(실행)하기 위한 문법적 기호입니다.
 * 6. { (중괄호 열기): 함수에 넘겨줄 설정 인자(옵션)를 객체 리터럴(Object Literal) 형태로 작성하기 시작합니다.
 * 7. variable:: 설정 객체의 첫 번째 속성 키(Key)로, 전역 CSS 변수명을 설정할 때 사용합니다.
 * 8. "--font-geist-mono": variable 속성의 값(Value)으로 사용할 텍스트 형식의 문자열입니다. CSS에서 var(--font-geist-mono) 형태로 쓸 수 있게 됩니다.
 * 9. , (쉼표): 객체의 첫 번째 속성과 두 번째 속성을 구분해주는 구분자입니다.
 * 10. subsets:: 설정 객체의 두 번째 속성 키(Key)로, 폰트 파일 용량을 줄이기 위해 어떤 언어셋만 압축해서 다운로드할지 지정하는 속성입니다.
 * 11. [ (대괄호 열기): 배열 리터럴(Array Literal) 작성을 시작하는 기호입니다. subsets는 여러 값을 담을 수 있는 배열 타입을 요구하기 때문입니다.
 * 12. "latin": 배열의 첫 번째 값인 문자열로, 라틴어(영문) 문자만 최적화하여 경량화 다운로드하겠다는 지시입니다.
 * 13. ] (대괄호 닫기): 배열 리터럴의 작성을 마칩니다.
 * 14. } (중괄호 닫기): 함수 인자로 넘겨줄 설정 객체 리터럴 작성을 마칩니다.
 * 15. ) (소괄호 닫기): Geist_Mono 함수의 인자 전달과 함수 호출을 종결합니다.
 * 16. ; (세미콜론): 폰트 상수 선언 및 생성 명령이 완전히 끝났음을 마크하는 기호입니다.
 */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


// 2.3: SEO 메타데이터 설정 (HTML의 <head> 태그 내부에 메타 태그로 주입됨)
/* 
 * [문법 요소 하나하나 상세 설명]
 * 1. export: 이 파일 외부에서 이 변수(metadata)를 가져다(import) 쓸 수 있도록 '내보내기'를 선언합니다. 
 *            Next.js 내부 엔진이 이 변수를 가져가 HTML <head> 태그를 생성할 때 활용하기 때문에 반드시 export해야 합니다.
 * 2. const: 자바스크립트/타입스크립트에서 재할당이 불가능한 상수를 선언하는 키워드입니다.
 * 3. metadata: Next.js 프레임워크가 약속한 특정 예약어 변수명입니다. 다른 이름(예: myMetadata)으로 적으면 Next.js가 읽지 못합니다.
 * 4. : Metadata: 타입스크립트(TypeScript)의 타입 선언(Type Annotation)입니다. 
 *                이 변수가 반드시 next 패키지에서 가져온 'Metadata' 타입 규격을 지켜야 함을 컴파일러에게 강제합니다. (오타나 잘못된 속성 입력을 방지함)
 * 5. =: 할당 연산자(Assignment Operator)로, 오른쪽에 명시된 객체 데이터를 왼쪽의 metadata 상수에 주입합니다.
 * 6. { ... }: 중괄호는 객체 리터럴(Object Literal)을 의미하며, 키-값(Key-Value) 쌍으로 구성된 데이터를 묶어줍니다.
 * 7. title:: 객체의 첫 번째 키(Key)로, 웹 브라우저 탭에 나타나는 제목(<title> 태그) 역할을 합니다.
 * 8. "Create Next App": 자바스크립트의 문자열(String) 데이터입니다. 큰따옴표("")로 감싸 텍스트임을 표현합니다.
 * 9. , (쉼표): 객체 내부의 속성(Property)들을 구분해주기 위한 구분자입니다.
 * 10. description:: 객체의 두 번째 키(Key)로, 검색 엔진이 읽는 웹사이트 보조 설명(<meta name="description" content="...">) 역할을 합니다.
 * 11. ; (세미콜론): 하나의 자바스크립트 명령 선언문(Statement)이 끝났음을 나타냅니다.
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


// 2.4: 루트 레이아웃 컴포넌트 (RootLayout)
// Next.js는 이 컴포넌트를 호출하고, 요청받은 페이지(children)를 body 태그 내부에 주입합니다.
/* 
 * [문법 요소 하나하나 상세 설명]
 * 1. export: 이 파일 외부(Next.js 내부 엔진 등)에서 이 함수를 불러갈 수 있도록 '내보내기'를 선언합니다.
 * 2. default: 이 파일이 갖는 단 하나의 '기본 내보내기' 대상임을 선언합니다. 다른 곳에서 중괄호 {} 없이 이름을 자유롭게 불러올 수 있습니다.
 * 3. function: 자바스크립트/타입스크립트의 '함수(Function)'를 선언하는 키워드입니다. React 컴포넌트는 JSX를 반환하는 특수한 함수입니다.
 * 4. RootLayout: 이 함수 컴포넌트의 이름(식별자)입니다. React 규칙 상 컴포넌트명은 반드시 대문자로 시작해야 합니다.
 * 5. ( (소괄호 열기): 함수의 매개변수(Parameters) 작성을 개시하는 기호입니다.
 * 6. { children }: 구조 분해 할당(Destructuring) 문법입니다. React는 인자로 props 객체({ children: ... })를 넘겨주는데, 
 *                 여기서 props.children 대신 children 변수로 직접 즉시 꺼내어 쓰겠다는 의미입니다.
 * 7. ): 매개변수 선언부의 닫는 소괄호입니다.
 * 8. : (콜론): 변수나 매개변수의 타입을 지정하기 시작하는 타입스크립트 문법입니다.
 * 9. Readonly<...>: 타입스크립트의 제네릭 유틸리티 타입으로, 내부 객체의 모든 속성을 '읽기 전용(Read-only)'으로 취급해 변경을 차단합니다.
 * 10. <: 제네릭 타입에 타입 옵션(매개변수)을 전달하기 시작하는 꺾쇠괄호입니다.
 * 11. { children: React.ReactNode; }: 전달받을 props 객체의 세부 스펙입니다. children 변수가 있고 그 타입이 React.ReactNode임을 정의합니다.
 * 12. React.ReactNode: 리액트가 화면에 출력할 수 있는 모든 구성 요소(HTML 태그, 문자열, 다른 리액트 컴포넌트 등)를 허용하는 광범위한 리액트 타입입니다.
 * 13. >: 제네릭 타입 옵션 지정을 마감하는 꺾쇠괄호입니다.
 * 14. { (중괄호 열기): 함수의 실제 코드를 작성하는 실행 블록(Body)의 시작입니다.
 * 15. return: 함수를 실행한 후 결과값(여기서는 JSX 템플릿)을 자신을 실행한 쪽으로 반환하는 지시어입니다.
 * 16. (: 반환할 JSX 템플릿 코드가 여러 줄에 걸쳐 있을 때 안정적인 반환과 세미콜론 자동 삽입(ASI) 오류를 방지하기 위해 씌워주는 기호입니다.
 * 17. <html lang="en" ...>: JSX(JavaScript XML) 문법으로 작성된 HTML html 루트 엘리먼트입니다.
 * 18. lang="en": 브라우저에 이 웹페이지의 기본 주 언어가 영어(en)임을 지시하는 속성(Attribute)입니다.
 * 19. className={ ... }: HTML의 class 속성에 대응되며, camelCase 표기를 사용합니다. 중괄호 {}를 사용해 자바스크립트 표현식을 연동합니다.
 * 20. ` ... `: 백틱 기호로 쓰인 자바스크립트의 템플릿 리터럴(Template Literal) 문법으로, 문자열 중간에 동적으로 변수를 직접 삽입할 수 있게 합니다.
 * 21. ${geistSans.variable}: 템플릿 리터럴 내부에서 geistSans 객체의 variable 속성 문자열(CSS 변수 이름)을 문자열로 동적 치환하는 문법입니다.
 * 22. <body ...> {children} </body>: HTML body 태그를 생성하고, 내부에 중괄호 {children}을 두어 
 *                                    방문한 특정 경로(예: page.tsx)의 페이지 컴포넌트를 동적으로 삽입하여 브라우저에 출력해 줍니다.
 * 23. ): return 문에 씌운 소괄호를 닫습니다.
 * 24. ;: return 문장과 함수 내 실행 선언문의 마침표 역할을 합니다.
 * 25. } (함수 중괄호 닫기): RootLayout 함수 컴포넌트 정의의 끝입니다.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // ReactNode 타입은 문자열, JSX, 컴포넌트 등 모든 렌더링 가능 대상을 포함합니다.
}>) {
  return (
    <html
      lang="en"
      // 폰트 클래스와 함께 전체 화면 높이(h-full) 및 폰트 부드럽게 설정(antialiased) 적용
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* 2.5: body 내부에서 {children}을 출력하여 개별 page.tsx의 내용이 렌더링되게 함 */}
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}


